// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjfPv4O4VbaIfg_6DmcjAPi9kwgeEPLM4',
    appId: '1:743500696201:web:522d0517c6a2f8dc0e9458',
    messagingSenderId: '743500696201',
    projectId: 'comictoonflutter',
    authDomain: 'comictoonflutter.firebaseapp.com',
    storageBucket: 'comictoonflutter.appspot.com',
    measurementId: 'G-WS94CG6QJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWLNtEx3QUJkEizDFN0jZM80zLwZsxrhI',
    appId: '1:743500696201:android:537edbdb2143db130e9458',
    messagingSenderId: '743500696201',
    projectId: 'comictoonflutter',
    storageBucket: 'comictoonflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmpOXBeCjV_jGwOpmIpg9HftS3dHGtjp8',
    appId: '1:743500696201:ios:4e1ed2274f5d18dc0e9458',
    messagingSenderId: '743500696201',
    projectId: 'comictoonflutter',
    storageBucket: 'comictoonflutter.appspot.com',
    iosClientId: '743500696201-lundcanf8mssjo4btmj3bl68caaid6al.apps.googleusercontent.com',
    iosBundleId: 'com.example.comicToonFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmpOXBeCjV_jGwOpmIpg9HftS3dHGtjp8',
    appId: '1:743500696201:ios:4e1ed2274f5d18dc0e9458',
    messagingSenderId: '743500696201',
    projectId: 'comictoonflutter',
    storageBucket: 'comictoonflutter.appspot.com',
    iosClientId: '743500696201-lundcanf8mssjo4btmj3bl68caaid6al.apps.googleusercontent.com',
    iosBundleId: 'com.example.comicToonFlutter',
  );
}
